name: audio_call
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_voximplant:
    path: ..
  shared_preferences: 2.5.2
  get_it: 8.0.3
  permission_handler: 11.4.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

