/*
 * Copyright (c) 2011-2020, Zingaya, Inc. All rights reserved.
 */

package com.voximplant.flutter_voximplant;

class VoximplantErrors {
    static final String ERROR_CLIENT_NOT_LOGGED_IN = "ERROR_CLIENT_NOT_LOGGED_IN";
    static final String ERROR_INCORRECT_OPERATION = "ERROR_INCORRECT_OPERATION";
    static final String ERROR_MISSING_PERMISSION = "ERROR_MISSING_PERMISSION";
    static final String ERROR_INTERNAL = "ERROR_INTERNAL";
    static final String ERROR_INVALID_ARGUMENTS = "ERROR_INVALID_ARGUMENTS";
    static final String ERROR_ALREADY_IN_THIS_STATE = "ERROR_ALREADY_IN_THIS_STATE";
    static final String ERROR_REJECTED = "ERROR_REJECTED";
    static final String ERROR_FUNCTIONALITY_IS_DISABLED = "ERROR_FUNCTIONALITY_IS_DISABLED";
    static final String ERROR_MEDIA_IS_ON_HOLD = "ERROR_MEDIA_IS_ON_HOLD";

    static final String ERROR_ACCOUNT_FROZEN = "ERROR_ACCOUNT_FROZEN";
    static final String ERROR_INVALID_PASSWORD = "ERROR_INVALID_PASSWORD";
    static final String ERROR_INVALID_STATE = "ERROR_INVALID_STATE";
    static final String ERROR_INVALID_USERNAME = "ERROR_INVALID_USERNAME";
    static final String ERROR_NETWORK_ISSUES = "ERROR_NETWORK_ISSUES";
    static final String ERROR_TIMEOUT = "ERROR_TIMEOUT";
    static final String ERROR_TOKEN_EXPIRED = "ERROR_TOKEN_EXPIRED";

    static final String ERROR_CONNECTION_FAILED = "ERROR_CONNECTION_FAILED";

    static class Messaging {
        static final String ERROR_SOMETHING_WENT_WRONG = "ERROR_SOMETHING_WENT_WRONG";
        static final String ERROR_TRANSPORT_MESSAGE_STRUCTURE_IS_WRONG = "ERROR_TRANSPORT_MESSAGE_STRUCTURE_IS_WRONG";
        static final String ERROR_EVENT_NAME_IS_UNKNOWN = "ERROR_EVENT_NAME_IS_UNKNOWN";
        static final String ERROR_CONVERSATION_DOES_NOT_EXIST = "ERROR_CONVERSATION_DOES_NOT_EXIST";
        static final String ERROR_MESSAGE_DOES_NOT_EXIST = "ERROR_MESSAGE_DOES_NOT_EXIST";
        static final String ERROR_MESSAGE_DELETED = "ERROR_MESSAGE_DELETED";
        static final String ERROR_ACL = "ERROR_ACL";
        static final String ERROR_ALREADY_IN_PARTICIPANTS_LIST = "ERROR_ALREADY_IN_PARTICIPANTS_LIST";
        static final String ERROR_PUBLIC_JOIN_IS_UNAVAILABLE = "ERROR_PUBLIC_JOIN_IS_UNAVAILABLE";
        static final String ERROR_CONVERSATION_DELETED = "ERROR_CONVERSATION_DELETED";
        static final String ERROR_USER_VALIDATION = "ERROR_USER_VALIDATION";
        static final String ERROR_USER_IS_NOT_IN_THE_PARTICIPANT_LIST = "ERROR_USER_IS_NOT_IN_THE_PARTICIPANT_LIST";
        static final String ERROR_MESSAGE_SIZE_EXCEEDS_LIMIT = "ERROR_MESSAGE_SIZE_EXCEEDS_LIMIT";
        static final String ERROR_USER_NOT_FOUND = "ERROR_USER_NOT_FOUND";
        static final String ERROR_IM_SERVICE_UNAVAILABLE = "ERROR_IM_SERVICE_UNAVAILABLE";
        static final String ERROR_METHOD_CALL_DISCARDED = "ERROR_METHOD_CALL_DISCARDED";
        static final String ERROR_EDITING_PARTICIPANTS_IN_DIRECT = "ERROR_EDITING_PARTICIPANTS_IN_DIRECT";
        static final String ERROR_LEAVING_DIRECT_NOT_ALLOWED = "ERROR_LEAVING_DIRECT_NOT_ALLOWED";
        static final String ERROR_SPECIFY_AT_LEAST_TWO_PARAMS = "ERROR_SPECIFY_AT_LEAST_TWO_PARAMS";
        static final String ERROR_SPECIFY_MAXIMUM_TWO_PARAMS = "ERROR_SPECIFY_MAXIMUM_TWO_PARAMS";
        static final String ERROR_REMOVING_FROM_DIRECT = "ERROR_REMOVING_FROM_DIRECT";
        static final String ERROR_ADDING_TO_DIRECT = "ERROR_ADDING_TO_DIRECT";
        static final String ERROR_LIMIT_PER_SECOND = "ERROR_LIMIT_PER_SECOND";
        static final String ERROR_LIMIT_PER_MINUTE = "ERROR_LIMIT_PER_MINUTE";
        static final String ERROR_DIRECT_CANNOT_BE_PUBLIC_OR_UBER = "ERROR_DIRECT_CANNOT_BE_PUBLIC_OR_UBER";
        static final String ERROR_NUMBER_OF_USERS_IN_DIRECT = "ERROR_NUMBER_OF_USERS_IN_DIRECT";
        static final String ERROR_WRONG_SEQUENCE_ARGUMENT = "ERROR_WRONG_SEQUENCE_ARGUMENT";
        static final String ERROR_FROM_GREATER_THAN_TO = "ERROR_FROM_GREATER_THAN_TO";
        static final String ERROR_REQUESTED_NUMBER_TOO_BIG = "ERROR_REQUESTED_NUMBER_TOO_BIG";
        static final String ERROR_REQUESTED_NUMBER_TOO_BIG_OR_0 = "ERROR_REQUESTED_NUMBER_TOO_BIG_OR_0";
        static final String ERROR_TIMEOUT = "ERROR_TIMEOUT";
        static final String ERROR_NOT_AUTHORIZED = "ERROR_NOT_AUTHORIZED";
        static final String ERROR_FAILED_TO_PROCESS_RESPONSE = "ERROR_FAILED_TO_PROCESS_RESPONSE";
        static final String ERROR_INTERNAL = "ERROR_INTERNAL";
        static final String ERROR_INVALID_ARGUMENTS = "ERROR_INVALID_ARGUMENTS";
        static final String ERROR_CLIENT_NOT_LOGGED_IN = "ERROR_CLIENT_NOT_LOGGED_IN";
        static final String ERROR_NOTIFICATION_EVENT_INCORRECT= "ERROR_NOTIFICATION_EVENT_INCORRECT";
    }
}